alias rm="trash"
alias vim="nvim"
alias openboard="openboard -lang hu"
alias upd="yay ; flatpak update"
alias nixrbd="sudo nixos-rebuild switch --flake ~/Nix"
alias nixupd="sudo nix flake update --flake ~/Nix; sudo nixos-rebuild switch --flake ~/Nix"
alias nixgb="sudo nix-collect-garbage -d; nix collect-garbage -d"
alias nixsyntax="~/Nix/alejandra ~/Nix/"
alias uxplay="uxplay -fps 75 -n PC -avdec -async -vsync no"
alias neofetch="fastfetch -c ~/.config/fastfetch/custom.jsonc"
#alias yay="paru"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias word="winapps manual winword.exe"
alias excel="winapps manual excel.exe"
alias ppt="winapps manual powerpnt.exe"
alias win="sudo ~/.scripts/winapps/bin/winapps manual"
alias 3utools="QT_QPA_PLATFORM=xcb /opt/apps/com.3u.3utools/run.sh"
alias idescriptor="QT_QPA_PLATFORM=xcb idescriptor-appimage"
alias sudo="doas"
