alias rm="trash"
alias vim="nvim"
alias code="env GTK_THEME=adw-gtk3-dark code"
alias openboard="openboard -lang hu"
alias upd="yay ; flatpak update"
alias nixrbd="sudo nixos-rebuild switch --flake ~/dotfiles/NixOS"
alias nixupd="sudo nix flake update --flake ~/dotfiles/NixOS; sudo nixos-rebuild switch --flake ~/dotfiles/NixOS"
alias nixgb="sudo nix-collect-garbage -d"
alias nixsyntax="~/dotfiles/NixOS/alejandra ~/dotfiles/NixOS/"
alias uxplay="uxplay -fps 75 -n PC -avdec -async -vsync no"
alias neofetch="fastfetch -c ~/.config/fastfetch/custom.jsonc"
alias kshare="nohup ~/goserver/ghfs -l 8181 --prefix /films -r /mnt/khdd/kshare &"
alias yay="paru"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias word="winapps manual winword.exe"
alias excel="winapps manual excel.exe"
alias ppt="winapps manual powerpnt.exe"
alias win="sudo ~/.scripts/winapps/bin/winapps manual"
alias rcrf="rclone rc vfs/refresh recursive=true"
